[build]
  base = "client"
  publish = "dist"
  command = "npm run build"
  environment = { NODE_VERSION = "20" }

[[redirects]]
  from = "/api/*"
  to = "https://assignment-4-api.onrender.com/api/:splat"
  status = 200
  force = true
